Shop_Auto/ViewModels/CarsListViewModel.cs
using Shop_Auto.Data.Models;
using System.Collections.Generic;

namespace Shop_Auto.ViewModels
{
    public class CarsListViewModel
    {
        public IEnumerable<Car> allCars { get; set; }
        public string CurrCategory { get; set; }
    }
}

Shop_Auto/ViewModels/HomeViewModel.cs
using Shop_Auto.Data.Models;
using System.Collections.Generic;

namespace Shop_Auto.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Car> favCars { get; set; }
    }
}

Shop_Auto/ViewModels/ShopCartViewModel.cs
using Shop_Auto.Data.Models;

namespace Shop_Auto.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart { get; set; }
    }
}

Shop_Auto/Controllers/CarsController.cs
using Shop_Auto.Data.interfaces;
using Shop_Auto.Data.Models;
using Shop_Auto.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Shop_Auto.Controllers
{
    public class CarsController : Controller
    {
        private readonly IAllCars _allCars; // variable for interfaces
        private readonly ICarsCategory _allCategories;

        // Constructor to read elements from interfaces
        public CarsController(IAllCars iAllCars, ICarsCategory iCarsCat)
        {
            _allCars = iAllCars;
            _allCategories = iCarsCat;
        }

        [Route("Cars/Index")]
        public IActionResult Search(string searchWord)
        {
            return View("Index", _allCars.Cars.Where(c => c.Name.Contains(searchWord, StringComparison.InvariantCultureIgnoreCase)));
        }

        [Route("Cars/List")]
        [Route("Cars/List/{category}")]
        // Function that returns ViewResult
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Car> cars = null;
            string currCategory = "";
            cars = _allCars.Cars.Where(i => i.Available);
            if (string.IsNullOrEmpty(category))
            {
                // .Available.Equals("True")).  //.OrderBy(i => i.Id)
                cars = cars.OrderBy(i => i.Id);
            }
            else
            {
                if (string.Equals("electric", category, System.StringComparison.OrdinalIgnoreCase))
                {
                    cars = cars.Where(i => i.Category.CategoryName.Equals("Electric Car")).OrderBy(i => i.Id);
                    currCategory = "electric";
                }
                else if (string.Equals("gasoline", category, System.StringComparison.OrdinalIgnoreCase))
                {
                    cars = cars.Where(i => i.Category.CategoryName.Equals("Gasoline Car")).OrderBy(i => i.Id);
                    currCategory = "gasoline";
                }
            }

            var carObj = new CarsListViewModel
            {
                allCars = cars,
                CurrCategory = currCategory
            };

            ViewBag.Title = "Page with cars";
            return View(carObj);
        }

    }
}

Shop_Auto/Controllers/HomeController.cs
using Shop_Auto.Data.interfaces;
using Shop_Auto.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Shop_Auto.Controllers
{
    public class HomeController : Controller
    {
        private IAllCars _carRep;

        public HomeController(IAllCars carRep)
        {
            _carRep = carRep;
        }

        public ViewResult Index()
        {
            var homeCars = new HomeViewModel
            {
                favCars = _carRep.GetFavCars
            };
            return View(homeCars);
        }

        public ViewResult Privacy()
        {
            return View();
        }

        public ViewResult Terms()
        {
            return View();
        }
    }
}

Shop_Auto/Controllers/OrderController.cs
using Shop_Auto.Data.interfaces;
using Shop_Auto.Data.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Shop_Auto.Controllers
{
    public class OrderController : Controller
    {

        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        public IActionResult Checkout()
        {
            shopCart.listShopItems = shopCart.getShopItems();

            if (shopCart.listShopItems.Count == 0)
            {
                ModelState.AddModelError("", "You should add items to the cart");
                ViewBag.Message = "You should add items to the cart";
                return View("Errors");
            }

            Dictionary<string, int> dStock = new Dictionary<string, int>();
            foreach (var item in shopCart.listShopItems)
                if (!dStock.ContainsKey(item.car.Name))
                    dStock.Add(item.car.Name, item.car.Stock);

            shopCart.DecreaseStock();
            string lista = "";

            foreach (var item in shopCart.listShopItems)
                if (item.car.Stock < 0)
                {
                    if (!lista.Contains(item.car.Name))
                    {
                        lista += dStock[item.car.Name].ToString() + " " + item.car.Name + ", ";
                    }
                    ModelState.AddModelError("", "We are not in possession of the amount of cars you want to order");
                }

            if (!lista.Equals(""))
            {
                lista = lista.Remove(lista.Length - 1);
                ViewBag.Message = "Sorry, we do not own the amount of cars you want to order. We have: " + lista + " car(s).";
                return View("Errors");
            }
            return View();
        }

        [HttpPost] // to work only after post method
        public IActionResult Checkout(Order order)
        {
            shopCart.listShopItems = shopCart.getShopItems();
            shopCart.DecreaseStock();
            if (ModelState.IsValid)
            {
                allOrders.CreateOrder(order);
                return RedirectToAction("Complete");
            }
            return View(order);
        }

        public IActionResult Complete()
        {
            shopCart.UpdateStock();
            shopCart.DeleteAllFromCart();
            ViewBag.Message = "Your order has been successfully processed. We will contact you soon to establish the billing data, payment method & delivery process of your order.";
            return View();
        }

    }
}

Shop_Auto/Controllers/ShopCartController.cs
using Shop_Auto.Data.interfaces;
using Shop_Auto.Data.Models;
using Shop_Auto.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Shop_Auto.Controllers
{
    public class ShopCartController : Controller
    {
        private IAllCars _carRep;
        private readonly ShopCart _shopCart;

        public ShopCartController(IAllCars carRep, ShopCart shopCart)
        {
            _carRep = carRep;
            _shopCart = shopCart;
        }

        public ViewResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.listShopItems = items;

            var obj1 = new ShopCartViewModel
            {
                shopCart = _shopCart
            };
            return View(obj1);
        }
        public RedirectToActionResult Add(int id)
        {
            var item = _carRep.Cars.FirstOrDefault(i => i.Id == id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult Delete(int id)
        {
            var item = _shopCart.getShopItems().FirstOrDefault(i => i.Id == id);
            if (item != null)
            {
                _shopCart.DeleteFromCart(item);
            }
            return RedirectToAction("Index");
        }
    }
}

Shop_Auto/Views/Cars/Index.cshtml
@model IEnumerable<Shop_Auto.Data.Models.Car>

<div class="container mt-4">
    @if (Model.Count() == 0)
    {
    <div class="preview container mt-4">
        <h2><strong>No cars were found based on your search.</strong></h2>
        </div>
        }
        else
        {
        <h1>Cars available based on your search:</h1>
        <div class="row mt-3 mb-2">

            @{ foreach (Car car in Model)
                {
                    @await Html.PartialAsync("AllCars", car) } }
        </div>
        }
    </div>

Shop_Auto/Views/Cars/List.cshtml
@model CarsListViewModel

    <div class="container mt-4">
        <h1>All available @Model.CurrCategory cars:</h1>
        <div class="row mt-4 mb-2">
            @{ foreach(Car car in Model.allCars) {
                    @await Html.PartialAsync("AllCars", car) } }
        </div>
        </div>

Shop_Auto/Views/Home/Index.cshtml
@model HomeViewModel

<div>
    @await Html.PartialAsync("Carousel")
</div>

<div class="container mt-4">
    <h2 class="mb-3">Get to know us: </h2>
    <h6 class="homeText">
        <p>At Best Motors Auto Sales, located in Cluj-Napoca, Cluj, we love what we do and want you to love your next vehicle. Our goal is to find you the pre-owned car you’ve been looking for at competitive and affordable prices. We focus 100% on our customers and believe car-buying should be a fun, hassle-free experience! We have a wide variety of quality vehicles that feature an assortment of options to meet any taste. Best of all, there are no hidden fees or costs. Buying a used car makes a whole lot of sense. One reason is that new cars, on average, lose 11 percent of their value the minute you drive them off the lot. But older cars depreciate more slowly, so you get more for your money when you buy a used car. When employing our services, your experience is sure to be the best!</p>
        <p>Come visit us at <span class="fst-italic">Calea Turzii 223, Cluj-Napoca 400495, Romania</span></p>
        <p>Phone: <span class="fst-italic">+40-264 438 820</span></p>
    </h6>
    <h2 class="m-2">Our best sellers: </h2>
    <div class="row mt-4 mb-2">
        @{ foreach(Car car in Model.favCars) {
                @await Html.PartialAsync("AllCars", car) } }
    </div>
</div>

Shop_Auto/Views/Home/Terms.cshtml
@{

    <div class="preview container mt-4 text-start">
        <h2><strong>Terms and Conditions</strong></h2>
        <p>Welcome to Best Motors Auto Sales!</p>
        <p>These terms and conditions outline the rules and regulations for the use of Best Motors Auto Sales' Website, located at https://localhost:44390/.</p>
        <p>By accessing this website we assume you accept these terms and conditions. Do not continue to use Best Motors Auto Sales if you do not agree to take all of the terms and conditions stated on this page.</p>
        <p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: "Client", "You" and "Your" refers to you, the person log on this website and compliant to the Company’s terms and conditions. "The Company", "Ourselves", "We", "Our" and "Us", refers to our Company. "Party", "Parties", or "Us", refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client’s needs in respect of provision of the Company’s stated services, in accordance with and subject to, prevailing law of Romania. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.</p>
        <h3><strong>Cookies</strong></h3>
        <p>We employ the use of cookies. By accessing Best Motors Auto Sales, you agreed to use cookies in agreement with the Best Motors Auto Sales' Privacy Policy. </p>
        <p>Most interactive websites use cookies to let us retrieve the user’s details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.</p>
        <h3><strong>License</strong></h3>
        <p>Unless otherwise stated, Best Motors Auto Sales and/or its licensors own the intellectual property rights for all material on Best Motors Auto Sales. All intellectual property rights are reserved. You may access this from Best Motors Auto Sales for your own personal use subjected to restrictions set in these terms and conditions.</p>
        <p>You must not:</p>
        <ul>
            <li>Republish material from Best Motors Auto Sales</li>
            <li>Sell, rent or sub-license material from Best Motors Auto Sales</li>
            <li>Reproduce, duplicate or copy material from Best Motors Auto Sales</li>
            <li>Redistribute content from Best Motors Auto Sales</li>
        </ul>
        <p>This Agreement shall begin on the date hereof. Our Terms and Conditions were created with the help of the <a href="https://www.termsandconditionsgenerator.com">Terms And Conditions Generator</a> and the <a href="https://www.generateprivacypolicy.com">Privacy Policy Generator</a>.</p>
        <p>Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. Best Motors Auto Sales does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the views and opinions of Best Motors Auto Sales,its agents and/or affiliates. Comments reflect the views and opinions of the person who post their views and opinions. To the extent permitted by applicable laws, Best Motors Auto Sales shall not be liable for the Comments or for any liability, damages or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.</p>
        <p>Best Motors Auto Sales reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive or causes breach of these Terms and Conditions.</p>
        <p>You warrant and represent that:</p>
        <ul>
            <li>You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;</li>
            <li>The Comments do not invade any intellectual property right, including without limitation copyright, patent or trademark of any third party;</li>
            <li>The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material which is an invasion of privacy</li>
            <li>The Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.</li>
        </ul>
        <p>You hereby grant Best Motors Auto Sales a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats or media.</p>
        <h3><strong>Hyperlinking to our Content</strong></h3>
        <p>The following organizations may link to our Website without prior written approval:</p>
        <ul>
            <li>Government agencies;</li>
            <li>Search engines;</li>
            <li>News organizations;</li>
            <li>Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses; and</li>
            <li>System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Web site.</li>
        </ul>
        <p>These organizations may link to our home page, to publications or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party’s site.</p>
        <p>We may consider and approve other link requests from the following types of organizations:</p>
        <ul>
            <li>commonly-known consumer and/or business information sources;</li>
            <li>dot.com community sites;</li>
            <li>associations or other groups representing charities;</li>
            <li>online directory distributors;</li>
            <li>internet portals;</li>
            <li>accounting, law and consulting firms; and</li>
            <li>educational institutions and trade associations.</li>
        </ul>
        <p>We will approve link requests from these organizations if we decide that: (a) the link would not make us look unfavorably to ourselves or to our accredited businesses; (b) the organization does not have any negative records with us; (c) the benefit to us from the visibility of the hyperlink compensates the absence of Best Motors Auto Sales; and (d) the link is in the context of general resource information.</p>
        <p>These organizations may link to our home page so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products or services; and (c) fits within the context of the linking party’s site.</p>
        <p>If you are one of the organizations listed in paragraph 2 above and are interested in linking to our website, you must inform us by sending an e-mail to Best Motors Auto Sales. Please include your name, your organization name, contact information as well as the URL of your site, a list of any URLs from which you intend to link to our Website, and a list of the URLs on our site to which you would like to link. Wait 2-3 weeks for a response.</p>
        <p>Approved organizations may hyperlink to our Website as follows:</p>
        <ul>
            <li>By use of our corporate name; or</li>
            <li>By use of the uniform resource locator being linked to; or</li>
            <li>By use of any other description of our Website being linked to that makes sense within the context and format of content on the linking party’s site.</li>
        </ul>
        <p>No use of Best Motors Auto Sales' logo or other artwork will be allowed for linking absent a trademark license agreement.</p>
        <h3><strong>iFrames</strong></h3>
        <p>Without prior approval and written permission, you may not create frames around our Webpages that alter in any way the visual presentation or appearance of our Website.</p>
        <h3><strong>Content Liability</strong></h3>
        <p>We shall not be hold responsible for any content that appears on your Website. You agree to protect and defend us against all claims that is rising on your Website. No link(s) should appear on any Website that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.</p>
        <h3><strong>Your Privacy</strong></h3>
        <p>Please read our Privacy Policy.</p>
        <h3><strong>Reservation of Rights</strong></h3>
        <p>We reserve the right to request that you remove all links or any particular link to our Website. You approve to immediately remove all links to our Website upon request. We also reserve the right to amen these terms and conditions and it’s linking policy at any time. By continuously linking to our Website, you agree to be bound to and follow these linking terms and conditions.</p>
        <h3><strong>Removal of links from our website</strong></h3>
        <p>If you find any link on our Website that is offensive for any reason, you are free to contact and inform us any moment. We will consider requests to remove links but we are not obligated to or so or to respond to you directly.</p>
        <p>We do not ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we promise to ensure that the website remains available or that the material on the website is kept up to date.</p>
        <h3><strong>Disclaimer</strong></h3>
        <p>To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website. Nothing in this disclaimer will:</p>
        <ul>
            <li>limit or exclude our or your liability for death or personal injury;</li>
            <li>limit or exclude our or your liability for fraud or fraudulent misrepresentation;</li>
            <li>limit any of our or your liabilities in any way that is not permitted under applicable law; or</li>
            <li>exclude any of our or your liabilities that may not be excluded under applicable law.</li>
        </ul>
        <p>The limitations and prohibitions of liability set in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer, including liabilities arising in contract, in tort and for breach of statutory duty.</p>
        <p>As long as the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.</p>
    </div>
}

Shop_Auto/Views/Order/Checkout.cshtml
@model Order
<div class="container mt-4">
    
    <h2>Complete Order</h2>
    <h6>Please enter your details in the given form:</h6>
    <div style="width:300px;" class="mx-auto row mb-5">
        <form asp-action="Checkout" method="post" class="form-horizontal">
            <div class="form-group">
                <label asp-for="name">Name:</label>
                <div class="col-12 mb-2">
                    <input asp-for="name" class="form-control" pattern="[A-Za-z' -]{1,32}"  required />
                    <details class="text-start text-muted small">
                        <summary class="small">Validation rules</summary>
                            <ul class="small">
                                <li>Can only contain letters and a few special characters ( ' and - )</li>
                                <li>Must be between 1 and 32 characters long</li>
                            </ul>
                                            </details>
                </div>
            </div>
            <div class="form-group mb-2">
                <label asp-for="surname">Surname:</label>
                <div class="col-12">
                    <input asp-for="surname" class="form-control" pattern="[A-Za-z' -]{1,32}" required />
                    <details class="text-start text-muted small">
                        <summary class="small">Validation rules</summary>
                            <ul class="small">
                                <li>Can only contain letters and a few special characters ( ' and - )</li>
                                <li>Must be between 1 and 32 characters long</li>
                            </ul>
                    </details>
                </div>
            </div>
            <div class="form-group mb-2">
                <label asp-for="address">Complete address:</label>
                <div class="col-12">
                    <input asp-for="address" class="form-control" pattern="[a-zA-Z0-9 /\\@@#$%&,().+-]{3,100}" required />
                    <details class="text-start text-muted small">
                        <summary class="small">Recommended format and validation vules</summary>
                        <small>Business's name (if applicable), Street address, City, State and ZIP code, Country</small>
                            <ul class="small">
                                <li>Can only contain letters, digits and a few special characters</li>
                                <li>Must be between 3 and 100 characters long</li>
                            </ul>
                        
                    </details>
                </div>
                
            </div>
            <div class="form-group mb-2">
                <label asp-for="phone">Phone number:</label>
                <div class="col-12">
                    <input asp-for="phone" class="form-control" pattern="\+\d{1,6}-\d{8,20}" required />
                    <details class="text-start text-muted small">
                        <summary class="small">Requested format: +(country code)-(phone)</summary>
                        <ul class="small">
                            <li>Country code must be between 1 and 6 digits long</li>
                            <li>Phone number must be between 8 and 20 digits long</li>
                        </ul>
                    </details>
                </div>
            </div>
            <div class="form-group mb-2">
                <label asp-for="email">Email:</label>
                <div class="col-12">
                    <input asp-for="email" class="form-control" pattern="[a-z0-9._%+-]+@@[a-z0-9.-]+\.[a-z]{2,4}$" required />
                    <div class="text-start text-muted small">
                        <small>Example: name.surname@domain.tld</small>
                    </div> 
                </div>
            </div>
            <input class="mt-2 btn btn-success" type="submit" value="Place Order" />

        </form>
        <h3>@ViewBag.Message</h3>
    </div>
</div>

Shop_Auto/Views/Order/Complete.cshtml
<div class="container mt-4">
    <h3>@ViewBag.Message</h3>
    </div>

Shop_Auto/Views/Order/Errors.cshtml
<div class="container mt-4">
    <h3>@ViewBag.Message</h3>
</div>

Shop_Auto/Views/Shared/AllCars.cshtml
@model Car

<div class="col-lg-4 mb-4">
    <div class="card p-0 h-100">
        <img class="rounded m-1" src="@Model.Img" alt="@Model.Name" />

        <div class="card-body border-top">
            <h2 class="mb-1">@Model.Name</h2>

            <p class="mb-2">
                @Model.ShortDesc <u>
                    <a style="color: black;" href=@(Model.Category.CategoryName == "Gasoline Car" ? "/Cars/List/gasoline" : "/Cars/List/electric")>@Model.Category.CategoryName</a>
                </u>
            </p>
            <div>@Model.LongDesc</div>
        </div>

        <div class="card-footer">
            <div class="d-flex justify-content-around">
                <p><b><abbr title="The stock is updated after the order is placed" class="initialism">Available</abbr>:</b> @Model.Stock @(Model.Stock == 1 ? "car" : "cars")</p>
                <p><b>Price:</b> @Model.Price.ToString("C", CultureInfo.CreateSpecificCulture("eu-ES"))</p>
            </div>
            <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="Add" asp-route-Id="@Model.Id">Add to Cart</a></p>
        </div>
    </div>
</div>

Shop_Auto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/style.css" type="text/css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <a class="navbar-brand text-warning ms-3" href="/">Best Motors Auto Sales</a>
            <div class="collapse navbar-collapse mx-auto" id="navbarCollapse">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item">
                        <a class="nav-link @(ViewContext.HttpContext.Request.Path.ToString() == "/" ? "active" : "")" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link @(ViewContext.HttpContext.Request.Path.ToString() == "/Cars/List" ? "active" : "")" href="/Cars/List">All Cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link @(ViewContext.HttpContext.Request.Path.ToString() == "/Cars/List/electric" ? "active" : "")" href="/Cars/List/electric">Electric Cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link @(ViewContext.HttpContext.Request.Path.ToString() == "/Cars/List/gasoline" ? "active" : "")" href="/Cars/List/gasoline">Gasoline Cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link @(ViewContext.HttpContext.Request.Path.ToString() == "/ShopCart" ? "active" : "")" href="/ShopCart">Shop Cart</a>
                    </li>

                </ul>

            </div>
          
            <form style="width: 250px;" class="input-group me-3 form-inline" asp-controller="Cars" asp-action="Search">
                 <input type="text" id="searchInput" class="form-control rounded me-1" name="searchWord" placeholder="Search" aria-label="Search"
                           aria-describedby="search-addon" />
                <button type="submit" id="searchBtn" class="btn btn-warning rounded"><img src="~/img/searchIcon.png" alt="..." width="22" /></button>
            </form>
        </nav>
    </header>

    <div class="text-center">
        @RenderBody()
    </div>

    <footer class="container">
        <p class="float-right" ><a href="#">Back to top</a></p>
        <p>© 1999 - 2022 Best Motors Auto Sales, Inc. · <a asp-controller="Home" asp-action="Privacy">Privacy</a> · <a asp-controller="Home" asp-action="Terms">Terms</a></p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <script src="~/js/script.js"></script>
</body>
</html>

Shop_Auto/Views/ShopCart/Index.cshtml
@model ShopCartViewModel

<div class="container mt-4">

    <h3 class="@(Model.shopCart.listShopItems.Count == 0 ? "" : "d-none")">You should add items to the cart</h3>

    @foreach(var el in Model.shopCart.listShopItems) {
        <div class="alert alert-warning mt-3 d-flex justify-content-between">
            <div class="item-info text-start">
                <b>Car:</b> @el.car.Name <br />
                <b>Price:</b> @el.car.Price.ToString("C", CultureInfo.CreateSpecificCulture("eu-ES")) <br />
            </div>
            <a asp-controller="ShopCart" asp-action="Delete" asp-route-Id="@el.Id">
                <img src="~/img/closeBtn.png" style="margin: 8px 0px; height: 32px;" alt="Delete item">
            </a>
        </div>
    }
    <hr />
    <!-- <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Complete Order</a> -->
    <button class="btn btn-success @(Model.shopCart.listShopItems.Count == 0 ? "d-none" : "")" onclick="location.href='@Url.Action("Checkout", "Order")'" @(Model.shopCart.listShopItems.Count == 0 ? "disabled" : "")>Complete Order</button>
</div>